//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimento_Dieta
    {
        public int DietaId { get; set; }
        public int AlimentoId { get; set; }
        public Nullable<decimal> CantidadDiaria { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Dieta Dieta { get; set; }
    }
}
