//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtiquetaNutricional
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public int AlimentoId { get; set; }
        public string TamanoPorcion { get; set; }
        public Nullable<decimal> Calorias { get; set; }
        public Nullable<decimal> PorcionesPorEnvase { get; set; }
        public Nullable<decimal> Sodio { get; set; }
        public Nullable<decimal> Azucares { get; set; }
        public Nullable<decimal> FibraDietetica { get; set; }
        public Nullable<decimal> VitaminaA { get; set; }
        public Nullable<decimal> VitaminaC { get; set; }
        public Nullable<decimal> Calcio { get; set; }
        public Nullable<decimal> Hierro { get; set; }
    
        public virtual Alimento Alimento { get; set; }
    }
}
