//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrores
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Modulo { get; set; }
        public string MensajeError { get; set; }
        public string Stacktrace { get; set; }
    }
}
