//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MacroBalanceEntities : DbContext
    {
        public MacroBalanceEntities()
            : base("name=MacroBalanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<Alimento_Dieta> Alimento_Dieta { get; set; }
        public virtual DbSet<Dieta> Dieta { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<EjercicioRealizado> EjercicioRealizado { get; set; }
        public virtual DbSet<EstadoEmocional> EstadoEmocional { get; set; }
        public virtual DbSet<LogErrores> LogErrores { get; set; }
        public virtual DbSet<Objetivo> Objetivo { get; set; }
        public virtual DbSet<PerfilDieta> PerfilDieta { get; set; }
        public virtual DbSet<PreferenciaAlimenticia> PreferenciaAlimenticia { get; set; }
        public virtual DbSet<Progreso> Progreso { get; set; }
        public virtual DbSet<Recordatorios> Recordatorios { get; set; }
        public virtual DbSet<RegistroAlimento> RegistroAlimento { get; set; }
        public virtual DbSet<Sugerencia> Sugerencia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
