//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MacroBalanceEntities1 : DbContext
    {
        public MacroBalanceEntities1()
            : base("name=MacroBalanceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimentoes { get; set; }
        public virtual DbSet<Alimento_Dieta> Alimento_Dieta { get; set; }
        public virtual DbSet<Dieta> Dietas { get; set; }
        public virtual DbSet<Ejercicio> Ejercicios { get; set; }
        public virtual DbSet<EjercicioRealizado> EjercicioRealizadoes { get; set; }
        public virtual DbSet<EstadoEmocional> EstadoEmocionals { get; set; }
        public virtual DbSet<LogErrore> LogErrores { get; set; }
        public virtual DbSet<Objetivo> Objetivoes { get; set; }
        public virtual DbSet<PreferenciaAlimenticia> PreferenciaAlimenticias { get; set; }
        public virtual DbSet<Progreso> Progresoes { get; set; }
        public virtual DbSet<Recordatorio> Recordatorios { get; set; }
        public virtual DbSet<RegistroAlimento> RegistroAlimentoes { get; set; }
        public virtual DbSet<Sugerencia> Sugerencias { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
