//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilDieta
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<decimal> CaloriasObjetivo { get; set; }
        public Nullable<decimal> Proteinas { get; set; }
        public Nullable<decimal> Carbohidratos { get; set; }
        public Nullable<decimal> Grasas { get; set; }
        public Nullable<decimal> Agua { get; set; }
        public Nullable<decimal> Ejercicio { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
