//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Cintura { get; set; }
        public Nullable<decimal> Cadera { get; set; }
        public Nullable<decimal> Pecho { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
