//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorios
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Nombre { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
