//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAlimento
    {
        public int Id { get; set; }
        public Nullable<int> DietaId { get; set; }
        public Nullable<int> AlimentoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Dieta Dieta { get; set; }
    }
}
