//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroBalance.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SugerenciaCicloMenstrual
    {
        public int Id { get; set; }
        public string Fase { get; set; }
        public string AlimentosRecomendados { get; set; }
        public string Beneficios { get; set; }
        public string SintomasRelacioandos { get; set; }
    }
}
